//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""19c319cc-9336-4094-8088-b4c95753cdcb"",
            ""actions"": [
                {
                    ""name"": ""MovePosition"",
                    ""type"": ""Value"",
                    ""id"": ""358c45fc-0d6e-48f0-8382-9ef498b0dc0b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveClick"",
                    ""type"": ""Button"",
                    ""id"": ""c166be95-dbd8-41e6-8b15-9b828400886c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cdce0e88-f5dd-48f9-8a02-a3d575437110"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0134a1f-0bdd-416c-8435-3251abea22d8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_MovePosition = m_Movement.FindAction("MovePosition", throwIfNotFound: true);
        m_Movement_MoveClick = m_Movement.FindAction("MoveClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private IMovementActions m_MovementActionsCallbackInterface;
    private readonly InputAction m_Movement_MovePosition;
    private readonly InputAction m_Movement_MoveClick;
    public struct MovementActions
    {
        private @PlayerActions m_Wrapper;
        public MovementActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePosition => m_Wrapper.m_Movement_MovePosition;
        public InputAction @MoveClick => m_Wrapper.m_Movement_MoveClick;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void SetCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterface != null)
            {
                @MovePosition.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnMovePosition;
                @MovePosition.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnMovePosition;
                @MovePosition.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnMovePosition;
                @MoveClick.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnMoveClick;
                @MoveClick.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnMoveClick;
                @MoveClick.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnMoveClick;
            }
            m_Wrapper.m_MovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovePosition.started += instance.OnMovePosition;
                @MovePosition.performed += instance.OnMovePosition;
                @MovePosition.canceled += instance.OnMovePosition;
                @MoveClick.started += instance.OnMoveClick;
                @MoveClick.performed += instance.OnMoveClick;
                @MoveClick.canceled += instance.OnMoveClick;
            }
        }
    }
    public MovementActions @Movement => new MovementActions(this);
    public interface IMovementActions
    {
        void OnMovePosition(InputAction.CallbackContext context);
        void OnMoveClick(InputAction.CallbackContext context);
    }
}
